application: hacktxf14
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest

handlers:
# static files
- url: /static
  static_dir: static

# json api
- url: /api/.*
  script: api_handlers.app

# main/web interface
- url: /.*
  script: web_handlers.app
